### ISSUE TITLE
Exception in getMountpath - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by GitANL** [VeeamHub/veeam-restore-point-utility#11]
**Describe the bug**
Not a bug per se, but I can only get as far as 'Mounting restore points', before getting the error: Exception in getMountpath - Object reference not set to an instance of an object

**To Reproduce**
Start the Veeam Restore Point Diff tool
*Wait for the backups to be retrieved*
Select a VM from a backup job
*Wait for restore points to be retrieved*
Select two different restore points, from the same storage location, taken 1 day apart (eg. point #1 is from 08-01-2024 and #2 is from 07-01-2024)
Select valid Mount Credentials and click 'Next'
*Wait for restore points to be retrieved*
The tool retrieves the restore points but fails when it is supposed to mount them

**Expected behavior**
That the backups are mounted and the tool displays a file list for both snapshots

**Screenshots**
![image](https://github.com/VeeamHub/veeam-restore-point-utility/assets/156080152/17d8f705-abaf-4bee-a688-f3d7a37f559b)

**Desktop (please complete the following information):**
 - OS: Server 2019
 - Version Veeam Backup & Replication 12.1.0.2131
 - Version Restore Point File Diff 2.0.3
 - .Net 4.8

**Additional context**

**Comment by ronnm-veeam** [comment]
Ok just want to double-check as I've never seen this error thrown in any other way.  The Server 2019 / VBR host is also your mount server I assume?  If "yes" please be absolutely certain you've selected mount credentials that are full Windows administrator on that Server 2019 instance and let me know what you find. Thanks!

**Comment by GitANL** [comment]
Thank you Ronn, you got it. :)
(I don't know how I missed that)

You're a star!

Best regards
Anders

**Comment by ronnm-veeam** [comment]
No worries! It's a common issue. I need to think about auto-selecting the credentials somehow...
