### ISSUE TITLE
Error enumerating available backups

### ISSUE THREAD

**Issue by sbailey8800** [VeeamHub/veeam-restore-point-utility#12]
Running this software as an administrator, I am met with this error:

"Error Veeam File Diff

Error enumerating available backups - unable to connect to the server with MFA-enabled user account. Execution environment cannot be initialized to Remote."

I have turned on MFA on Veeam Backup and Replication.  Can this software be run without disabling MFA?

**Expected behavior**
I would like to utilize this software without disabling MFA.

**Screenshots**
![error - windows restore point diff](https://github.com/VeeamHub/veeam-restore-point-utility/assets/129212834/04d897f0-2013-4a6e-8756-b7d5ef6f95db)

**Desktop (please complete the following information):**
 - OS: Windows Server Standard 2019
 - Browser N/A
 - Version [Version 10.0.17763.5206]

**Additional context**

**Comment by ronnm-veeam** [comment]
Unfortunately at this time no.  The application is utilizing the .NET Runspace class to leverage our Powershell interface and currently the data integration API cmdlets are not operational w/in an MFA-enabled user context (see [https://helpcenter.veeam.com/docs/backup/vsphere/mfa.html?ver=120#requirements-and-limitations](url)).  May be best to create a user account/role w/in VBR w/o MFA enabled so you don't have to disable MFA altogether.

**Comment by sbailey8800** [comment]
Got it, thank you for responding!

**Comment by ronnm-veeam** [comment]
You're very welcome!
