### ISSUE TITLE
Firefox browser and VirusTotal report MSI contains trojan malware

### ISSUE THREAD

**Issue by chunkysloth** [VeeamHub/veeam-restore-point-utility#13]
FireFox warned me on download, which I allowed, then uploaded setup.msi to VirusTotal which 14 engines report as malware:

https://www.virustotal.com/gui/file/ab8532e3384cfd4b34994b6083d99b176ccaea8d2fbdcb8451c5bd1d5f1315ca/detection

Would like to try but this seems like a lot of false positives.

**Comment by carceneaux** [comment]
Hi @chunkysloth,

It's common for viruses/trojans to be found in setup files. The source code used to compile [setup.msi](https://github.com/VeeamHub/veeam-restore-point-utility/releases) can also be found in this repository.

If there are concerns that setup.msi is malware, I recommend reviewing the code in this repository and compiling from source.

Thanks for visiting VeeamHub!
