### ISSUE TITLE
Restore Points list empty

### ISSUE THREAD

**Issue by jwhit265** [VeeamHub/veeam-restore-point-utility#5]
List of restore points is not populated and is blank.

To reproduce this I run the program as administrator and select the desired windows workload and click select. On the next page it appears to attempt to load but eventually nothing happens and no restore points are listed.

I expect there to be a list of restore points to select from after selecting the windows workload.

I am using the latest version of the tool 2.0.1.
I am running server 2022
I am running it on the same server as the backups

**Comment by ronnm-veeam** [comment]
Apologies for the slow response on this end. Were you ever able to resolve the issue?

**Comment by jwhit265** [comment]
No problems at all. Yes list still appears empty unfortunately.On 7 Oct 2023, at 12:08 am, Ronn Martin ***@***.***> wrote:﻿
Apologies for the slow response on this end. Were you ever able to resolve the issue?

**Comment by ronnm-veeam** [comment]
Sorry for the slow response. Could you try running this PowerShell command and see if it returns the list you're expecting?

`Get-VBRRestorePoint -Name <VMNAME> | Select-Object VmName, CreationTime, Type, Id, {$_.FindChainRepositories().Name}`

**Comment by ronnm-veeam** [comment]
I've added a few fixes. Please give this version a try when you're able - [https://github.com/ronnm-veeam/veeam-restore-point-utility/releases/tag/v2.03](url)

**Comment by ronnm-veeam** [comment]
Since I've not heard anything further assuming this is resolved by the new version...
