### ISSUE TITLE
Could support for Agent backups be added?

### ISSUE THREAD

**Issue by dcrithyne** [VeeamHub/veeam-restore-point-utility#6]
A large percentage of our backups are Veeam Agent for Windows jobs (in Workstation mode, I see Server mode agents are already available), would it be feasible to provide restore point comparison for these?

**Comment by ronnm-veeam** [comment]
So sorry for the slow response!  If this is something you're still interested in I'll block out some time to expand the eligible backup types.  Please let me know

**Comment by ronnm-veeam** [comment]
Can you try importing the workstation backups into the VBR server and then installing/running this version of the application? [https://github.com/ronnm-veeam/veeam-restore-point-utility/releases/tag/v2.0.2](url)

**Comment by dcrithyne** [comment]
Thanks for the update Ronn.

Unfortunately I'm still not seeing our workstation agents. I don't quite follow your comment on importing the backups, they're managed by the VBR server, but in Workstation mode, with restore points visible in the VBR console under Backups > Disk

The utility seems to be backup job centric? I see one of our long since deleted jobs in the utility, and 2 instances of our "Low Frequency" job (Which I likely deleted and recreated with the same name at some point in the past)

![image](https://github.com/VeeamHub/veeam-restore-point-utility/assets/94335371/f6b4375c-d875-4028-8a53-8e5517d040f8)

**Comment by ronnm-veeam** [comment]
Ah yes it does source backups via VBR job so I can see how it would probably miss workstation managed backups.  I'll try to carve out time to look at this in detail sometime the next couple weeks.  Yes and I see the same phantom job appearance in my own lab. Will see if I can get those filtered as well.  Appreciate the feedback!

**Comment by ronnm-veeam** [comment]
Ok it looks like I was simply failing to account for a particular job type.  Please give this version a go and let me know if it solves the problem - [https://github.com/ronnm-veeam/veeam-restore-point-utility/releases/tag/v2.03](url)

**Comment by dcrithyne** [comment]
I can now see restore points from Workstation agent backups, thank you Ronn!

**Comment by ronnm-veeam** [comment]
Great!  I'll get it promoted up to VeeamHub soon but feel free to continue to use the version from my repo
