### ISSUE TITLE
exception in get mount path

### ISSUE THREAD

**Issue by YushenkoAM** [VeeamHub/veeam-restore-point-utility#9]
![123](https://github.com/VeeamHub/veeam-restore-point-utility/assets/152920286/05e7acac-9d83-4722-aa13-00fe93747b70)
Hello.
I get this error, when try ty mount restore point

**Comment by ronnm-veeam** [comment]
Generally this points to an issue with the credentials selected in the prior step. Be sure you're selecting credentials with admin privilege on the mount server. The credentials selected don't need to be applicable to the actual workload you're running the comparison against.

**Comment by ronnm-veeam** [comment]
Since I've not heard anything further assuming this is resolved with the application of correct credentials...
